# Catppuccin Mocha
interface_branding:
interface_help_hidden: yes

wallpaper: boot():/limine/blue-dragon-girl.jpg
wallpaper_style: stretched

term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
term_background: 001e1e2e
term_foreground: cdd6f4
term_background_bright: 585b70
term_foreground_bright: cdd6f4
term_margin: 400
term_margin_gradient: 50
interface_resolution: 2560x1440

timeout: 5

/Arch
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: root=PARTUUID=<CHANGEIT> zswap.enabled=0 rw rootfstype=<CHANGEIT(btrfs)>
    module_path: boot():/initramfs-linux.img

/Windows
    protocol: efi_chainload
    image_path: guid(<CHANGEIT>):/EFI/Microsoft/Boot/bootmgfw.efi
